version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  app:
    container_name: sf.app
    build: .docker/php
    volumes:
      - .:/app
      - ./var/logs:/app/var/logs
      - ./var/cache.:/app/var/cache
  nginx:
    container_name: sf.nginx
    build: .docker/nginx
    ports:
      - "81:80"
    environment:
      - VIRTUAL_HOST=symfony-dev.local
    volumes_from:
      - app
